version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: AWSSDK.IotData
    versions:
    - 3.5.0.61
    - 3.5.0.65
    - 3.5.0.67
    - 3.5.0.70
    - 3.5.0.71
    - 3.5.0.72
    - 3.5.0.75
    - 3.5.0.76
    - 3.5.0.78
    - 3.7.0.1
    - 3.7.0.12
    - 3.7.0.7
    - 3.7.0.9
  - dependency-name: Google.Apis.Calendar.v3
    versions:
    - 1.49.0.2187
    - 1.49.0.2224
    - 1.50.0.2224
    - 1.50.0.2237
    - 1.51.0.2237
    - 1.51.0.2272
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Amazon.Lambda.TestUtilities
    versions:
    - 1.2.0
  - dependency-name: Amazon.Lambda.Serialization.Json
    versions:
    - 1.8.0
  - dependency-name: Amazon.Lambda.Core
    versions:
    - 1.2.0
