version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: dotnet --version && dotnet build
      - run: dotnet test

  deploy:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run:
          name: add ~/.dotnet/tools to $PATH
          command: |
            echo 'export PATH=$PATH:/root/.dotnet/tools'  >> $BASH_ENV
            source $BASH_ENV
      - run: dotnet tool install -g Amazon.Lambda.Tools
      - run: |
          apt update
          apt install -y zip
      - run:
          name: deploy
          command: dotnet lambda deploy-serverless --disable-interactive true -pl roommate-lambda --stack-name roommate-dev --s3-bucket roommate-deploy --region us-east-1

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
